-- TŞYS (Talep ve Şikâyet Yönetim Sistemi) — başlangıç şeması
--
-- public şeması: 5 tablo (departments, users, requests, results, notifications),
-- 22 RLS politikası, 3 yardımcı fonksiyon (current_user_role, current_user_department,
-- handle_new_user) — `docker exec supabase-db pg_dump -U postgres --schema-only
-- --schema=public -d postgres` ile dışa aktarıldı ve Supabase Studio üzerinden elle
-- kurulan yapıyla karşılaştırılıp doğrulandı.
--
-- auth.users üzerindeki on_auth_user_created trigger'ı pg_dump'ın kapsamı dışında
-- kaldığı (auth şeması public değil) için bu dosyanın sonuna elle eklendi.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: current_user_department(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.current_user_department() RETURNS bigint
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  select department_id from public.users where id = auth.uid();
$$;


ALTER FUNCTION public.current_user_department() OWNER TO postgres;

--
-- Name: current_user_role(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.current_user_role() RETURNS text
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  select role from public.users where id = auth.uid();
$$;


ALTER FUNCTION public.current_user_role() OWNER TO postgres;

--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  insert into public.users (id, email, full_name, role, department_id)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    'vatandas',
    null
  );
  return new;
end;
$$;


ALTER FUNCTION public.handle_new_user() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: TABLE departments; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.departments IS 'Kurumdakim birimlerin verisini tutan tablo';


--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    request_id uuid NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: TABLE notifications; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.notifications IS 'bildirimler (müdür onayladımı , vatandaş sonucu gördümü)';


--
-- Name: requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    category text NOT NULL,
    status text DEFAULT 'acik'::text NOT NULL,
    requester_type text NOT NULL,
    department_id bigint NOT NULL,
    created_by uuid NOT NULL,
    assigned_to uuid
);


ALTER TABLE public.requests OWNER TO postgres;

--
-- Name: TABLE requests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.requests IS 'talep ve arızaların verisi';


--
-- Name: results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.results (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    report_text text NOT NULL,
    resolved_by uuid NOT NULL,
    approval_status text DEFAULT 'beklemede'::text NOT NULL,
    approved_by uuid,
    request_id uuid NOT NULL
);


ALTER TABLE public.results OWNER TO postgres;

--
-- Name: TABLE results; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.results IS 'sonuçlandırmalar';


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text NOT NULL,
    full_name text NOT NULL,
    role text NOT NULL,
    department_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.users IS 'kullanıcılar (admin , personel , vatandaş vs)';


--
-- Name: departments departments_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_name_key UNIQUE (name);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: notifications notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (id);


--
-- Name: results results_request_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_request_id_key UNIQUE (request_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: requests requests_assigned_to_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: requests requests_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: requests requests_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE RESTRICT;


--
-- Name: results results_approved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: results results_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id) ON DELETE CASCADE;


--
-- Name: results results_resolved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: users users_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- Name: users users_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: departments Birimlerin Görünürlüğü; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Birimlerin Görünürlüğü" ON public.departments FOR SELECT USING (true);


--
-- Name: requests acan_kisi_henuz_atanmamisken_duzenleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY acan_kisi_henuz_atanmamisken_duzenleyebilir ON public.requests FOR UPDATE USING (((created_by = auth.uid()) AND (assigned_to IS NULL))) WITH CHECK (((created_by = auth.uid()) AND (assigned_to IS NULL)));


--
-- Name: requests acan_kisi_kendi_talebini_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY acan_kisi_kendi_talebini_gorebilir ON public.requests FOR SELECT USING ((created_by = auth.uid()));


--
-- Name: requests admin_hepsini_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY admin_hepsini_gorebilir ON public.requests FOR SELECT USING ((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'admin'::text));


--
-- Name: requests admin_her_seyi_guncelleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY admin_her_seyi_guncelleyebilir ON public.requests FOR UPDATE USING ((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'admin'::text)) WITH CHECK ((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'admin'::text));


--
-- Name: users admin_herkesi_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY admin_herkesi_gorebilir ON public.users FOR SELECT USING ((public.current_user_role() = 'admin'::text));


--
-- Name: results atanan_personel_beklemedeyken_duzenleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY atanan_personel_beklemedeyken_duzenleyebilir ON public.results FOR UPDATE USING (((resolved_by = auth.uid()) AND (approval_status = 'beklemede'::text))) WITH CHECK (((resolved_by = auth.uid()) AND (approval_status = 'beklemede'::text)));


--
-- Name: results atanan_personel_rapor_ekleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY atanan_personel_rapor_ekleyebilir ON public.results FOR INSERT WITH CHECK (((resolved_by = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.requests
  WHERE ((requests.id = results.request_id) AND (requests.assigned_to = auth.uid()))))));


--
-- Name: requests birim_calisanlari_biriminin_taleplerini_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY birim_calisanlari_biriminin_taleplerini_gorebilir ON public.requests FOR SELECT USING (((department_id = ( SELECT users.department_id
   FROM public.users
  WHERE (users.id = auth.uid()))) AND (( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = ANY (ARRAY['personel'::text, 'mudur'::text]))));


--
-- Name: departments; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

--
-- Name: requests giris_yapmis_herkes_talep_acabilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY giris_yapmis_herkes_talep_acabilir ON public.requests FOR INSERT WITH CHECK ((created_by = auth.uid()));


--
-- Name: results ilgili_talebi_gorebilen_sonucu_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ilgili_talebi_gorebilen_sonucu_gorebilir ON public.results FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.requests
  WHERE ((requests.id = results.request_id) AND ((requests.created_by = auth.uid()) OR ((requests.department_id = ( SELECT users.department_id
           FROM public.users
          WHERE (users.id = auth.uid()))) AND (( SELECT users.role
           FROM public.users
          WHERE (users.id = auth.uid())) = ANY (ARRAY['personel'::text, 'mudur'::text]))) OR (( SELECT users.role
           FROM public.users
          WHERE (users.id = auth.uid())) = 'admin'::text))))));


--
-- Name: notifications kendi_bildirimini_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY kendi_bildirimini_gorebilir ON public.notifications FOR SELECT USING ((user_id = auth.uid()));


--
-- Name: notifications kendi_bildirimini_okundu_yapabilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY kendi_bildirimini_okundu_yapabilir ON public.notifications FOR UPDATE USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));


--
-- Name: users kendi_kaydini_olusturabilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY kendi_kaydini_olusturabilir ON public.users FOR INSERT WITH CHECK ((id = auth.uid()));


--
-- Name: users kendi_profilini_görebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "kendi_profilini_görebilir" ON public.users FOR SELECT USING ((id = auth.uid()));


--
-- Name: users kendi_profilini_güncelleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "kendi_profilini_güncelleyebilir" ON public.users FOR UPDATE USING ((id = auth.uid())) WITH CHECK (((id = auth.uid()) AND (role = ( SELECT users_1.role
   FROM public.users users_1
  WHERE (users_1.id = auth.uid()))) AND (NOT (department_id IS DISTINCT FROM ( SELECT users_1.department_id
   FROM public.users users_1
  WHERE (users_1.id = auth.uid()))))));


--
-- Name: users mudur_biriminin_personelini_gorebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY mudur_biriminin_personelini_gorebilir ON public.users FOR SELECT USING (((department_id = public.current_user_department()) AND (public.current_user_role() = 'mudur'::text)));


--
-- Name: requests mudur_durum_ve_atama_guncelleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY mudur_durum_ve_atama_guncelleyebilir ON public.requests FOR UPDATE USING (((department_id = ( SELECT users.department_id
   FROM public.users
  WHERE (users.id = auth.uid()))) AND (( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'mudur'::text))) WITH CHECK (((department_id = ( SELECT users.department_id
   FROM public.users
  WHERE (users.id = auth.uid()))) AND (( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'mudur'::text)));


--
-- Name: results mudur_onay_verebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY mudur_onay_verebilir ON public.results FOR UPDATE USING (((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'mudur'::text) AND (EXISTS ( SELECT 1
   FROM public.requests
  WHERE ((requests.id = results.request_id) AND (requests.department_id = ( SELECT users.department_id
           FROM public.users
          WHERE (users.id = auth.uid())))))))) WITH CHECK (((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'mudur'::text) AND (EXISTS ( SELECT 1
   FROM public.requests
  WHERE ((requests.id = results.request_id) AND (requests.department_id = ( SELECT users.department_id
           FROM public.users
          WHERE (users.id = auth.uid()))))))));


--
-- Name: notifications; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

--
-- Name: requests; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

--
-- Name: results; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;

--
-- Name: departments sadece_admin_ekleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY sadece_admin_ekleyebilir ON public.departments FOR INSERT WITH CHECK ((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'admin'::text));


--
-- Name: departments sadece_admin_güncelleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "sadece_admin_güncelleyebilir" ON public.departments FOR UPDATE USING ((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'admin'::text)) WITH CHECK ((( SELECT users.role
   FROM public.users
  WHERE (users.id = auth.uid())) = 'admin'::text));


--
-- Name: notifications sistem_bildirim_ekleyebilir; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY sistem_bildirim_ekleyebilir ON public.notifications FOR INSERT WITH CHECK (false);


--
-- Name: users; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: FUNCTION current_user_department(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.current_user_department() TO anon;
GRANT ALL ON FUNCTION public.current_user_department() TO authenticated;
GRANT ALL ON FUNCTION public.current_user_department() TO service_role;


--
-- Name: FUNCTION current_user_role(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.current_user_role() TO anon;
GRANT ALL ON FUNCTION public.current_user_role() TO authenticated;
GRANT ALL ON FUNCTION public.current_user_role() TO service_role;


--
-- Name: FUNCTION handle_new_user(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.handle_new_user() TO anon;
GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;
GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;


--
-- Name: TABLE departments; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.departments TO anon;
GRANT ALL ON TABLE public.departments TO authenticated;
GRANT ALL ON TABLE public.departments TO service_role;


--
-- Name: SEQUENCE departments_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.departments_id_seq TO anon;
GRANT ALL ON SEQUENCE public.departments_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.departments_id_seq TO service_role;


--
-- Name: TABLE notifications; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.notifications TO anon;
GRANT ALL ON TABLE public.notifications TO authenticated;
GRANT ALL ON TABLE public.notifications TO service_role;


--
-- Name: TABLE requests; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.requests TO anon;
GRANT ALL ON TABLE public.requests TO authenticated;
GRANT ALL ON TABLE public.requests TO service_role;


--
-- Name: TABLE results; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.results TO anon;
GRANT ALL ON TABLE public.results TO authenticated;
GRANT ALL ON TABLE public.results TO service_role;


--
-- Name: TABLE users; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.users TO anon;
GRANT ALL ON TABLE public.users TO authenticated;
GRANT ALL ON TABLE public.users TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--



--
-- Name: on_auth_user_created; Type: TRIGGER; Schema: auth
-- auth.users'a yeni kayıt düştüğünde public.users'a otomatik profil
-- (role='vatandas', department_id=null) oluşturur. pg_dump --schema=public
-- bu trigger'ı yakalamaz çünkü auth.users, public şemasının dışındadır.
--

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
